name: emoji_mart
version: 1.0.2
description: Typed over_react component wrappers for the JS emoji-mart library.
homepage: https://github.com/computmaxer/emoji_mart_dart

environment:
  sdk: '>=2.11.0 <3.0.0'

dependencies:
  js: ^0.6.3
  over_react: ^4.1.0
  react: ^6.1.6

dev_dependencies:
  build_runner: ">=1.6.2 <2.0.0"
  build_web_compilers: ">=2.6.1 <3.0.0"
